// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using voidcat_api.Data;

#nullable disable

namespace voidcat_api.Migrations
{
    [DbContext(typeof(TarotDbContext))]
    partial class TarotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("voidcat_api.Models.TarotCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TarotCardTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TarotCardTypeId");

                    b.ToTable("TarotCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Interpretation = "New beginnings, optimism, trust in life",
                            Name = "The Fool",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Interpretation = "Resourcefulness, power, inspired action",
                            Name = "The Magician",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            Interpretation = "Intuition, unconscious knowledge, potential",
                            Name = "The High Priestess",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            Interpretation = "Fertility, femininity, beauty, nature, abundance",
                            Name = "The Empress",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            Interpretation = "Authority, father figure, structure, solid foundation",
                            Name = "The Emperor",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 5,
                            Interpretation = "Spiritual wisdom, religious beliefs, conformity, tradition",
                            Name = "The Hierophant",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 6,
                            Interpretation = "Relationships, choices, alignment of values",
                            Name = "The Lovers",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 7,
                            Interpretation = "Control, willpower, victory, assertion, determination",
                            Name = "The Chariot",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 8,
                            Interpretation = "Strength, courage, patience, control",
                            Name = "Strength",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 9,
                            Interpretation = "Soul-searching, introspection, being alone, inner guidance",
                            Name = "The Hermit",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 10,
                            Interpretation = "Good luck, karma, life cycles, destiny, a turning point",
                            Name = "Wheel of Fortune",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 11,
                            Interpretation = "Justice, fairness, truth, cause and effect, law",
                            Name = "Justice",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 12,
                            Interpretation = "Pause, surrender, letting go, new perspectives",
                            Name = "The Hanged Man",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 13,
                            Interpretation = "Endings, change, transformation, transition",
                            Name = "Death",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 14,
                            Interpretation = "Balance, moderation, patience, purpose",
                            Name = "Temperance",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 15,
                            Interpretation = "Addiction, sexuality, attachment, restrictions",
                            Name = "The Devil",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 16,
                            Interpretation = "Sudden change, upheaval, chaos, revelation, awakening",
                            Name = "The Tower",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 17,
                            Interpretation = "Hope, faith, purpose, renewal, spirituality",
                            Name = "The Star",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 18,
                            Interpretation = "Illusion, fear, anxiety, subconscious, intuition",
                            Name = "The Moon",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 19,
                            Interpretation = "Positivity, fun, warmth, success, vitality",
                            Name = "The Sun",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 20,
                            Interpretation = "Judgment, rebirth, inner calling, absolution",
                            Name = "Judgment",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 21,
                            Interpretation = "Completion, integration, accomplishment, travel",
                            Name = "The World",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 22,
                            Interpretation = "New feelings, spirituality, intuition",
                            Name = "Ace of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 23,
                            Interpretation = "Partnership, unity, love",
                            Name = "Two of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 24,
                            Interpretation = "Celebration, friendship, creativity, collaborations",
                            Name = "Three of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 25,
                            Interpretation = "Meditation, contemplation, apathy, reevaluation",
                            Name = "Four of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 26,
                            Interpretation = "Loss, bereavement, regret, disappointment",
                            Name = "Five of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 27,
                            Interpretation = "Nostalgia, childhood memories, innocence, joy",
                            Name = "Six of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 28,
                            Interpretation = "Choices, confusion, illusion, fantasy",
                            Name = "Seven of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 29,
                            Interpretation = "Disappointment, abandonment, withdrawal, escapism",
                            Name = "Eight of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 30,
                            Interpretation = "Satisfaction, emotional stability, luxury",
                            Name = "Nine of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 31,
                            Interpretation = "Contentment, family, harmony, marriage",
                            Name = "Ten of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 32,
                            Interpretation = "A messenger, creative beginnings, synchronicity",
                            Name = "Page of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 33,
                            Interpretation = "Romance, charm, 'Knight in shining armor'",
                            Name = "Knight of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 34,
                            Interpretation = "Compassion, calm, comfort, healing",
                            Name = "Queen of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 35,
                            Interpretation = "Emotionally balanced, compassionate, diplomatic",
                            Name = "King of Cups",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 36,
                            Interpretation = "New ideas, clarity, breakthroughs, mental clarity",
                            Name = "Ace of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 37,
                            Interpretation = "Difficult choices, indecision, stalemate",
                            Name = "Two of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 38,
                            Interpretation = "Heartbreak, emotional pain, sorrow",
                            Name = "Three of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 39,
                            Interpretation = "Rest, recovery, contemplation, peace",
                            Name = "Four of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 40,
                            Interpretation = "Conflict, tension, loss, defeat",
                            Name = "Five of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 41,
                            Interpretation = "Transition, change, rite of passage",
                            Name = "Six of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 42,
                            Interpretation = "Deception, trickery, tactics, and strategy",
                            Name = "Seven of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 43,
                            Interpretation = "Restriction, limitation, confusion, powerlessness",
                            Name = "Eight of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 44,
                            Interpretation = "Anxiety, worry, fear, depression",
                            Name = "Nine of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 45,
                            Interpretation = "Endings, loss, crisis, betrayal",
                            Name = "Ten of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 46,
                            Interpretation = "Curiosity, restless energy, thirst for knowledge",
                            Name = "Page of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 47,
                            Interpretation = "Action, impulsiveness, defending beliefs",
                            Name = "Knight of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 48,
                            Interpretation = "Complexity, perceptiveness, clear mindedness",
                            Name = "Queen of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 49,
                            Interpretation = "Intellectual power, authority, truth",
                            Name = "King of Swords",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 50,
                            Interpretation = "Inspiration, new opportunities, growth, potential",
                            Name = "Ace of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 51,
                            Interpretation = "Future planning, progress, decisions, discovery",
                            Name = "Two of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 53,
                            DisplayOrder = 52,
                            Interpretation = "Preparation, foresight, enterprise, expansion",
                            Name = "Three of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 54,
                            DisplayOrder = 53,
                            Interpretation = "Celebration, joy, harmony, relaxation, homecoming",
                            Name = "Four of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 55,
                            DisplayOrder = 54,
                            Interpretation = "Competition, conflict, strife, tension",
                            Name = "Five of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 56,
                            DisplayOrder = 55,
                            Interpretation = "Success, acclaim, achievement, leadership",
                            Name = "Six of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 57,
                            DisplayOrder = 56,
                            Interpretation = "Perseverance, defensive, maintaining control",
                            Name = "Seven of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 58,
                            DisplayOrder = 57,
                            Interpretation = "Movement, fast paced change, action, alignment",
                            Name = "Eight of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 59,
                            DisplayOrder = 58,
                            Interpretation = "Resilience, courage, persistence, test of faith",
                            Name = "Nine of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 60,
                            DisplayOrder = 59,
                            Interpretation = "Burden, extra responsibility, hard work, completion",
                            Name = "Ten of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 61,
                            DisplayOrder = 60,
                            Interpretation = "Enthusiasm, exploration, discovery, free spirit",
                            Name = "Page of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 62,
                            DisplayOrder = 61,
                            Interpretation = "Energy, passion, inspired action, adventure",
                            Name = "Knight of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 63,
                            DisplayOrder = 62,
                            Interpretation = "Confidence, independence, home, vitality",
                            Name = "Queen of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 64,
                            DisplayOrder = 63,
                            Interpretation = "Natural-born leader, vision, entrepreneur",
                            Name = "King of Wands",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 65,
                            DisplayOrder = 64,
                            Interpretation = "Opportunity, prosperity, new venture",
                            Name = "Ace of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 66,
                            DisplayOrder = 65,
                            Interpretation = "Balance, multitasking, time management",
                            Name = "Two of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 67,
                            DisplayOrder = 66,
                            Interpretation = "Collaboration, learning, implementation",
                            Name = "Three of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 68,
                            DisplayOrder = 67,
                            Interpretation = "Conservation, security, frugality, control",
                            Name = "Four of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 69,
                            DisplayOrder = 68,
                            Interpretation = "Need, poverty, insecurity, worry",
                            Name = "Five of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 70,
                            DisplayOrder = 69,
                            Interpretation = "Generosity, giving, receiving, sharing wealth",
                            Name = "Six of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 71,
                            DisplayOrder = 70,
                            Interpretation = "Patience, waiting, profitability, investment",
                            Name = "Seven of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 72,
                            DisplayOrder = 71,
                            Interpretation = "Apprenticeship, craftsmanship, skill, diligence",
                            Name = "Eight of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 73,
                            DisplayOrder = 72,
                            Interpretation = "Luxury, self-sufficiency, culmination",
                            Name = "Nine of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 74,
                            DisplayOrder = 73,
                            Interpretation = "Wealth, inheritance, family, establishment",
                            Name = "Ten of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 75,
                            DisplayOrder = 74,
                            Interpretation = "Ambition, desire, diligence, new beginnings",
                            Name = "Page of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 76,
                            DisplayOrder = 75,
                            Interpretation = "Efficiency, hard work, responsibility, conservatism",
                            Name = "Knight of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 77,
                            DisplayOrder = 76,
                            Interpretation = "Practicality, creature comforts, financial security",
                            Name = "Queen of Pentacles",
                            TarotCardTypeId = 1
                        },
                        new
                        {
                            Id = 78,
                            DisplayOrder = 77,
                            Interpretation = "Abundance, prosperity, security, ambition",
                            Name = "King of Pentacles",
                            TarotCardTypeId = 1
                        });
                });

            modelBuilder.Entity("voidcat_api.Models.TarotCardSpread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TarotCardSpreads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The single card pull helps answer simple questions.",
                            Name = "Single Card"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Three Card Spread is simple yet effective for straightforward questions.",
                            ImageUrl = "assets/img/three-card.png",
                            Name = "Three Card"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Celtic Cross Spread provides in-depth insights into complex situations.",
                            ImageUrl = "assets/img/celtic-cross.png",
                            Name = "Celtic Cross"
                        });
                });

            modelBuilder.Entity("voidcat_api.Models.TarotCardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TarotCardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Rider–Waite Tarot"
                        });
                });

            modelBuilder.Entity("voidcat_api.Models.TarotCard", b =>
                {
                    b.HasOne("voidcat_api.Models.TarotCardType", "TarotCardType")
                        .WithMany()
                        .HasForeignKey("TarotCardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TarotCardType");
                });
#pragma warning restore 612, 618
        }
    }
}
