name: Trigger auto deployment for voidcat

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/voidcat-AutoDeployTrigger-b650b67a-85d7-4efb-b5a1-e10c0e62e136.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VOIDCAT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VOIDCAT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VOIDCAT_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.VOIDCAT_REGISTRY_PASSWORD }}" | docker login voidcat.azurecr.io -u ${{ secrets.VOIDCAT_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t voidcat.azurecr.io/voidcat:${{ github.sha }} -f voidcat-api/Dockerfile voidcat-api

      - name: Push Docker image
        run: |
          docker push voidcat.azurecr.io/voidcat:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: voidcat
          resourceGroup: voidcat
          imageToDeploy: voidcat.azurecr.io/voidcat:${{ github.sha }}
